# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlaceSearch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PlaceSearch
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'PlaceSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PlaceSearch-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PlaceSearch-tvOS

  target 'PlaceSearch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
